# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_Usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('Token', models.CharField(max_length=32)),
                ('Nombre', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Clave', models.CharField(max_length=32)),
                ('Perfil', models.CharField(max_length=2)),
                ('Estado', models.CharField(max_length=1)),
            ],
        ),
    ]
